[package]
name = "masterik/garage-life"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Packet = "ddust1n/packet@0.0.1"
TopbarPlus = "1foreverhd/topbarplus@3.4.0"
ZonePlus = "mattschrubb/zoneplus@3.2.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"